#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d III ""
#bspc monitor -d IV ""
#bspc monitor -d V ""

bspc config border_width         4
bspc config window_gap          15

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
#bspc rule -a nomacs desktop='^3'
#bspc rule -a Alacritty desktop='^1'
#bspc rule -a Spotify desktop='^10'
bspc rule -a mplayer2 state=floating
bspc rule -a textshot state=fullscreen
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Alacritty state=floating
bspc rule -a Peek state=floating
bspc rule -a Rofi state=floating
bspc rule -a Screenkey manage=off

# Autostart
# Set display from arandr saved script
# sh ~/.screenlayout/screen.sh &
# Bar
sh ~/polybar-collection/launch.sh &
# Notifications
# /usr/bin/dunst &
# Polkit
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
feh --bg-scale ~/.wallpaper/wallpaper.png
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/ &
# Picom
picom -fb &
# picom -b &
# Network Applet
# nm-applet --indicator &
# Cursor
xsetroot -cursor_name left_ptr &
# Low battery notifier
# ~/.config/bspwm/scripts/low_bat_notifier.sh &
# screenkey
screenkey --font-color white --bg-color grey --opacity 0  -p fixed -g 90%x6%+40%-10% -f "DejaVu Sans Mono Bold" -M &
# auto redshift
redshift -b 1.0 -l 40.78:114.9 -t 5700:3600 -g 0.8 -m randr -v &
# fix idea 
# wmname LG3D
#application
/home/yimi/.config/conky/Auva/start.sh &
#dropbox &
fcitx5 &
/usr/local/share/clash/cfw &
alacritty &
nomacs &
firefox &
spotify &
# 限制屏幕亮度
light -N 10 &
wmname LG3D &
blueman-manager &
